package com.azur.howfar.payment

data class FlutterWaveResponse(
    var status: String = "",
    var message: String = "",
    var data: Data = Data(),
)

data class Data (
    var id: Float = 0f,
    var txRef: String = "",
    var orderRef: String = "",
    var flwRef: String = "",
    var redirectUrl: String = "",
    var device_fingerprint: String = "",
    var settlement_token: String = "",
    var cycle: String = "",
    var amount: Float = 0f,
    var charged_amount: Float = 0f,
    var appfee: Float = 0f,
    var merchantfee: Float = 0f,
    var merchantbearsfee: Float = 0f,
    var chargeResponseCode: String = "",
    var raveRef: String = "",
    var chargeResponseMessage: String = "",
    var authModelUsed: String = "",
    var currency: String = "",
    var iP: String = "",
    var narration: String = "",
    var status: String = "",
    var modalauditid: String = "",
    var vbvrespmessage: String = "",
    var authurl: String = "",
    var vbvrespcode: String = "",
    var acctvalrespmsg: String = "",
    var acctvalrespcode: String = "",
    var paymentType: String = "",
    var paymentPlan: String = "",
    var paymentPage: String = "",
    var paymentId: String = "",
    var fraud_status: String = "",
    var charge_type: String = "",
    var is_live: Float = 0f,
    var retry_attempt: String = "",
    var getpaidBatchId: String = "",
    var createdAt: String = "",
    var updatedAt: String = "",
    var deletedAt: String = "",
    var customerId: Float = 0f,
    var accountId: Float = 0f,
    var customer_id: Float = 0f,
    var customer_phone: Float = 0f,
    var customer_fullName: Float = 0f,
    var customer_email: Float = 0f,
    var customer_createdAt: Float = 0f,
    var customer_updatedAt: Float = 0f,
    var customer_deletedAt: Float = 0f,
    var customer_AccountId: Float = 0f,
    var meta: ArrayList<Any> = arrayListOf(),
    var flwMeta: FlwMeta = FlwMeta(),
)
data class FlwMeta(
    var id: String = ""
)